spring:
  # OUTPUT
  output:
    ansi:
      enabled: detect
  # DATASOURCE
  datasource:
    url: jdbc:mysql://localhost:3306/bdo-loot-tracker
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:liquibase/master.xml
  # JPA
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: false
  # JACKSON
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
      write-durations-as-timestamps: true

server:
  port: 0

logging:
  level:
    root: info
    org.springframework: info
    org.springframework.security: debug
    org.hibernate: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com.example.demo: debug

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.int}
    hostname: localhost

security:
  secret-key: GkD0wnqHaN6y5peyf0

